#!/usr/bin/env python3
"""Generate the runtime catalog for independently downloaded Dune2R art."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path


DISPLAY_NAMES = {
    "gravel": "Gravel Terrain Remastered",
    "sand": "Sand Terrain Remastered",
    "harkonnendevastator": "Harkonnen Devastator Remastered",
    "ordostank": "Ordos Tank Remastered",
    "harkonneninfantry": "Harkonnen Infantry Remastered",
    "refinery": "Atreides Refinery Remastered",
}


def git_revision(repo: Path, revision: str = "HEAD") -> str:
    return subprocess.check_output(
        ["git", "rev-parse", revision], cwd=repo, text=True
    ).strip()


def git_blob(repo: Path, revision: str, path: Path) -> bytes:
    relative = path.relative_to(repo).as_posix()
    return subprocess.check_output(["git", "show", f"{revision}:{relative}"], cwd=repo)


VERSION_KEY = "Version="


def target_lines(catalog: str) -> list[str]:
    """The lines that identify the artwork target.

    Comments and the publication counter are presentation and ordering, not target:
    everything else - revision, base URL, pack metadata and every expected file path,
    size and hash - is what the runtime has to treat as one target.
    """
    kept = []
    for line in catalog.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(VERSION_KEY):
            continue
        kept.append(stripped)
    return kept


def catalog_version(catalog: str) -> int:
    """Publication counter recorded in a catalog; 0 for legacy catalogs without one."""
    for line in catalog.splitlines():
        stripped = line.strip()
        if stripped.startswith(VERSION_KEY):
            value = stripped[len(VERSION_KEY):].strip()
            return int(value) if value.isdigit() else 0
    return 0


def publication_version(target: str, previous: str | None) -> int:
    """Next publication counter for this target.

    Git dates cannot order publications: two asset commits can carry the same
    committer date, and a commit made later can carry an earlier one. The catalog
    therefore keeps its own counter, carried forward from the catalog being replaced.
    An unchanged target keeps its number so regeneration is idempotent, a changed
    target takes the next one, and a legacy catalog without a counter starts at 1.
    """
    if previous is None:
        return 1
    number = catalog_version(previous)
    if number <= 0:
        return 1
    return number if target_lines(previous) == target_lines(target) else number + 1


def build_catalog(repo: Path, revision: str, previous: str | None = None) -> str:
    """Catalog text for `revision`, numbered after the catalog in `previous`."""
    revision = git_revision(repo, revision)
    prefix = "mods/Dune2R/graphics_hd/units/"
    paths = subprocess.check_output(
        ["git", "ls-tree", "-r", "--name-only", "-z", revision, "--", prefix], cwd=repo
    ).decode("utf-8").split("\0")
    units = {}
    for path in paths:
        if not path or path.endswith("/.gitkeep"):
            continue
        unit, separator, relative = path[len(prefix):].partition("/")
        if separator and not unit.startswith("."):
            units.setdefault(unit, []).append(relative)
    lines = [
        "# Generated by scripts/generate-dune2r-asset-catalog.py",
        "# URLs are pinned to an immutable public game commit.",
        "[Catalog]",
        "Schema=1",
        f"Revision={revision}",
        "BaseURL=https://raw.githubusercontent.com/dunecity-project/dunecity/"
        f"{revision}/mods/Dune2R/graphics_hd/units",
        f"PackCount={len(units)}",
        "",
    ]

    for pack_index, (unit, files) in enumerate(sorted(units.items())):
        lines.extend(
            [
                f"[Pack.{pack_index}]",
                f"ID={unit}",
                f"DisplayName={DISPLAY_NAMES.get(unit, unit)}",
                "Variant=remastered",
                f"Unit={unit}",
                f"FileCount={len(files)}",
            ]
        )
        for file_index, relative in enumerate(sorted(files)):
            blob = git_blob(repo, revision, repo / prefix / unit / relative)
            digest = hashlib.sha256(blob).hexdigest()
            lines.append(f"File.{file_index}={relative}|{len(blob)}|{digest}")
        lines.append("")

    target = "\n".join(lines)
    version = publication_version(target, previous)
    lines.insert(lines.index(f"Revision={revision}") + 1, f"Version={version}")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--revision", help="Immutable Git revision containing the assets")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    repo = args.repo.resolve()
    revision = git_revision(repo, args.revision or "HEAD")
    output = args.output or repo / "mods/Dune2R/asset-catalog.ini"
    # The catalog being replaced carries the counter forward, so an unchanged target
    # keeps its published number and a changed one is unmistakably newer.
    previous = output.read_text(encoding="ascii") if output.is_file() else None
    output.parent.mkdir(parents=True, exist_ok=True)
    catalog = build_catalog(repo, revision, previous)
    output.write_text(catalog, encoding="ascii", newline="\n")
    print(f"Wrote {output} pinned to {revision} as publication {catalog_version(catalog)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
